### ISSUE TITLE
printf leaks memory with newlib 3.3.0 and heap_useNewlib_ST.c

### ISSUE THREAD

**Issue by Miceuz** [DRNadler/FreeRTOS_helpers#7]
First of all, thank you for digging deep and providing this solution. 

I am experiencing weird random crashes with FreeRTOS using heap_4.c. Tracing __wrap_malloc and __wrap__malloc_r I can see that newlib malloc is called from printf (I am printing %s and %lu values, not floats, but I can see malloc called even for printf calls with no arguments). I use STM32CubeIDE Version: 1.6.1, that uses newlib 3.3.0.

Alfter long search I have found your solution which explains the issue pretty good. 

Now when I use heap_useNewlib_ST.c FreeRTOS+TCP leaks memory by just accepting and closing connection. Interestingly enough, It does not leak memory when using heap_4.c. Any ideas where I could look to debug this issue?

**Comment by Miceuz** [comment]
After all, printf is responsible for the leak. I have removed all calls to <strdio.h> printf and replaced that with https://github.com/mpaland/printf and the leaks have stopped!

**Comment by DRNadler** [comment]
Miceuz, printf allocates some memory for each reetrancy context (with FreeRTOS and heap_useNewlib, for each task) in which it is called. Are you certain there is a leak, as opposed to the normal allocation? This memory would only be freed when the task exits.
Hope that helps clear things up,
Best Regards, Dave

**Comment by Miceuz** [comment]
In my particular use case printf is called from a task and a task exits. It's a client connection task that is being created upon client connecting to a port. The code is almost verbatim from FreeRTOS example:

A task that listens for connection:

```C
static void cli_server_listener_task(void *Parameters) {
	(void) Parameters;

	Socket_t ListeningSocket, ConnectedSocket;
	static const TickType_t ReceiveTimeout = portMAX_DELAY;
	struct freertos_sockaddr BindAddress;
	const BaseType_t Backlog = 1;

	ListeningSocket = FreeRTOS_socket(FREERTOS_AF_INET, FREERTOS_SOCK_STREAM,
	FREERTOS_IPPROTO_TCP);
	configASSERT(ListeningSocket != FREERTOS_INVALID_SOCKET);

	FreeRTOS_setsockopt(ListeningSocket, 0, FREERTOS_SO_RCVTIMEO,
			&ReceiveTimeout, sizeof(ReceiveTimeout));

#if( ipconfigUSE_TCP_WIN == 1 )
	WinProperties_t WinProps;

	WinProps.lTxBufSize = ipconfigTCP_TX_BUFFER_LENGTH;
	WinProps.lTxWinSize = configCLI_SERVER_TX_WINDOW_SIZE;
	WinProps.lRxBufSize = ipconfigTCP_RX_BUFFER_LENGTH;
	WinProps.lRxWinSize = configCLI_SERVER_RX_WINDOW_SIZE;

	FreeRTOS_setsockopt(ListeningSocket, 0, FREERTOS_SO_WIN_PROPERTIES,
			(void*) &WinProps, sizeof(WinProps));
#endif /* ipconfigUSE_TCP_WIN */

	BindAddress.sin_port = cliserverPORT_NUMBER;
	BindAddress.sin_port = FreeRTOS_htons(BindAddress.sin_port);
	FreeRTOS_bind(ListeningSocket, &BindAddress, sizeof(BindAddress));
	FreeRTOS_listen(ListeningSocket, Backlog);

	for (;;) {
		struct freertos_sockaddr Client;
		socklen_t Size = sizeof(Client);

		ConnectedSocket = FreeRTOS_accept(ListeningSocket, &Client, &Size);

		if ((ConnectedSocket != FREERTOS_NO_SOCKET)
				&& (ConnectedSocket != FREERTOS_INVALID_SOCKET)) {
			xTaskCreate(cli_server_client_task, "CliServerClient",
					UsedStackSize, (void*) ConnectedSocket, tskIDLE_PRIORITY,
					NULL);
		}
	}
}
```

a client task:

```C
static void cli_server_client_task(void *Parameters) {
	Socket_t ConnectedSocket = (Socket_t) Parameters;
	char OutputString[cliserverMAX_OUTPUT_LEN];
	TickType_t LastReceivedTime = xTaskGetTickCount();

	memset(OutputString, 0, cliserverMAX_OUTPUT_LEN);

	uint8_t *RxBuffer = pvPortMalloc(ipconfigTCP_MSS);

	if (NULL == RxBuffer) {
		FreeRTOS_closesocket(ConnectedSocket);
		vTaskDelete(NULL);
	}

	FreeRTOS_setsockopt(ConnectedSocket, 0, FREERTOS_SO_RCVTIMEO,
			&ReceiveTimeout, sizeof(ReceiveTimeout));
	FreeRTOS_setsockopt(ConnectedSocket, 0, FREERTOS_SO_SNDTIMEO, &SendTimeout,
			sizeof(SendTimeout));

	snprintf(OutputString, cliserverMAX_OUTPUT_LEN, "\n\n***************** IMC Online ********************\n\n#");

	FreeRTOS_send(ConnectedSocket, (const void*) OutputString,
			strlen((const char*) OutputString), 0);

	for (;;) {
		memset(RxBuffer, 0x00, ipconfigTCP_MSS);
		int32_t BytesReceived = FreeRTOS_recv(ConnectedSocket, RxBuffer, ipconfigTCP_MSS, FREERTOS_MSG_DONTWAIT);

		if (BytesReceived > 0) {
			LastReceivedTime = xTaskGetTickCount();

			if (BytesReceived < (BaseType_t) sizeof(RxBuffer)) {
				RxBuffer[BytesReceived] = '\0';
			}

			while (BytesReceived && ((RxBuffer[BytesReceived - 1] == ftpASCII_CR) || (RxBuffer[BytesReceived - 1] == ftpASCII_LF))) {
				RxBuffer[--BytesReceived] = '\0';
			}

			printf("CLI:[%s] Heap:%lu\n", RxBuffer, xPortGetFreeHeapSize());

			uint32_t MoreBytes = pdFALSE;
			do{
				MoreBytes = FreeRTOS_CLIProcessCommand( (const char * const) RxBuffer, (char *) OutputString, cliserverMAX_OUTPUT_LEN  );
				FreeRTOS_send(ConnectedSocket, (const void*) OutputString, strlen((const char*) OutputString), 0);
			} while(MoreBytes);

			FreeRTOS_send(ConnectedSocket, "\n#", strlen("\n#"), 0);

		} else if (BytesReceived < 0) {
//			//socket is closed?
			break;
		} else {
			if(xTaskGetTickCount() - LastReceivedTime > 10000) {
				printf("No comm timeout!!!\n");
				sprintf(OutputString, cliserverMAX_OUTPUT_LEN, "Well, goodbye...\n");
				FreeRTOS_send(ConnectedSocket, (const void*) OutputString,
						strlen((const char*) OutputString), 0);
				break;
			}
		}
	}

	printf("CLI: Socket closed, shutting down\n");
	socket_shutdown(ConnectedSocket, RxBuffer);
	vPortFree(RxBuffer);
	vTaskDelete(NULL);
}

static void socket_shutdown(Socket_t Socket, uint8_t *RxBuffer) {

	TickType_t TimeOnShutdown = xTaskGetTickCount();

	FreeRTOS_shutdown(Socket, FREERTOS_SHUT_RDWR);

    /* The RTOS task will get here if an error is received on a read.  Ensure the
    socket has shut down (indicated by FreeRTOS_recv() returning a FREERTOS_EINVAL
    error before closing the socket). */

    while( FreeRTOS_recv( Socket, RxBuffer, ipconfigTCP_MSS, 0 ) >= 0 ) {
        /* Wait for shutdown to complete.  If a receive block time is used then
        this delay will not be necessary as FreeRTOS_recv() will place the RTOS task
        into the Blocked state anyway. */
        printf(".");
    	vTaskDelay(10);

        if((xTaskGetTickCount() - TimeOnShutdown) < cliserverSHUTDOWN_DELAY) {
        	printf("\n\n\nSocket shutdown timeout!!\n");
        	break;
        }
        /* Note - real applications should implement a timeout here, not just
        loop forever. */
    }

	BaseType_t r = FreeRTOS_closesocket(Socket);
}
```

The leak is happening in the `cli_server_client_task` - on every new connection heap is smaller and smaller until malloc assert is fired by heap_useNewlib. It's loosing 444 bytes on every connection. I have tried minimizing both the test functionality and the available code till I pinpointed that to printf. I.e. it's enough just to open and close connection.

I guess it's worth noting that I am using FreeRTOS v202012.00 from FreeRTOS github.

**Comment by DRNadler** [comment]
Thanks for the detail Miceuz; that all certainly looks proper.
Can you please tell me the version of newlib you are using?
I will try to investigate later today; standby...

**Comment by Miceuz** [comment]
It's in the title - newlib 3.3.0 :)

**Comment by DRNadler** [comment]
Sorry, Thanks!

**Comment by Miceuz** [comment]
BTW ST seem to have done something right, as now I have just moved to FrooRTOS infrastructure provided by them and I seems I am stable now. 

I.e. I was using FreeRTOS provided by FreeRTOS, not by ST, so the original problem I had was in a bit exotic setup

**Comment by DRNadler** [comment]
Are you now using newlib's printf without leaks?

**Comment by Miceuz** [comment]
It seems printf is fine, also printing floats from task, just did a separate test to confirm that. 

But in general I have spoken too soon - just got a crash from `mktime`

**Comment by Miceuz** [comment]
FIY this is with stock ST FreeRTOS on STM32CubeIDE Version: 1.6.1 
![image](https://user-images.githubusercontent.com/533263/114591038-1f58be80-9c92-11eb-8396-2b8089f2a52f.png)

**Comment by DRNadler** [comment]
You did `#define configUSE_NEWLIB_REENTRANT 1` in FreeRTOSConfig.h right?

**Comment by Miceuz** [comment]
Yes, I did.

**Comment by DRNadler** [comment]
You did `#define configUSE_NEWLIB_REENTRANT 1` in FreeRTOSConfig.h right?
